In [1]:
import pandas as pd
df=pd.read_csv("FAOSTAT_data_5-22-2018 (1).csv")
#Ce fichier comporte la population totale de tous les pays pour les années 2010 2011 2012 et 2013
#La Chine comme agrégat, faisant partie de la séléction normale de tous les pays, est enlevée de la sélection
#dans ce fichier et tous les autres avec lesquels je travaillerai.

In [2]:
df=df.groupby("Année").get_group(2013)

In [3]:
#Population totale en 2013, en milliers de gens
df.sum()["Valeur"]

6997326

In [4]:
#Pour des réutilisations futures, je vais la "nettoyer" ici
Popu2013=df.drop(columns=["Code Domaine","Domaine","Code Pays","Code Élément","Élément","Code Produit","Produit","Code Année","Année","Unité","Symbole","Description du Symbole"])
Popu2013["Population"]=Popu2013["Valeur"]*1000
Popu2013=Popu2013.drop(columns="Valeur")
Popu2013=Popu2013.reset_index().drop(columns="index")

In [5]:
Popu2013

                                       Pays  Population
0                               Afghanistan    30552000
1                            Afrique du Sud    52776000
2                                   Albanie     3173000
3                                   Algérie    39208000
4                                 Allemagne    82727000
5                                    Angola    21472000
6                        Antigua-et-Barbuda       90000
7                           Arabie saoudite    28829000
8                                 Argentine    41446000
9                                   Arménie     2977000
10                                Australie    23343000
11                                 Autriche     8495000
12                              Azerbaïdjan     9413000
13                                  Bahamas      377000
14                               Bangladesh   156595000
15                                  Barbade      285000
16                                  Bélarus     9357000
17                                 Belgique    11104000
18                                   Belize      332000
19                                    Bénin    10323000
20                                 Bermudes       65000
21          Bolivie (État plurinational de)    10671000
22                       Bosnie-Herzégovine     3829000
23                                 Botswana     2021000
24                                   Brésil   200362000
25                        Brunéi Darussalam      418000
26                                 Bulgarie     7223000
27                             Burkina Faso    16935000
28                               Cabo Verde      499000
29                                 Cambodge    15135000
..                                      ...         ...
144                    Sao Tomé-et-Principe      193000
145                                 Sénégal    14133000
146                                  Serbie     9511000
147                            Sierra Leone     6092000
148                               Slovaquie     5450000
149                                Slovénie     2072000
150                                  Soudan    37964000
151                               Sri Lanka    21273000
152                                   Suède     9571000
153                                  Suisse     8078000
154                                Suriname      539000
155                               Swaziland     1250000
156                             Tadjikistan     8208000
157                                   Tchad    12825000
158                           Tchéquie (la)    10702000
159                               Thaïlande    67011000
160                             Timor-Leste     1133000
161                                    Togo     6817000
162                       Trinité-et-Tobago     1341000
163                                 Tunisie    10997000
164                            Turkménistan     5240000
165                                 Turquie    74933000
166                                 Ukraine    45239000
167                                 Uruguay     3407000
168                                 Vanuatu      253000
169  Venezuela (République bolivarienne du)    30405000
170                                Viet Nam    91680000
171                                   Yémen    24407000
172                                  Zambie    14539000
173                                Zimbabwe    14150000

[174 rows x 2 columns]